# Generated by Django 5.1.4 on 2024-12-16 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userlanguage_is_primary_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLanguage',
        ),
    ]
